# Generated by Django 4.2.11 on 2026-02-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('midnight', 'Midnight'), ('emerald', 'Emerald'), ('sunset', 'Sunset'), ('light', 'Light')], default='default', max_length=20),
        ),
    ]
