# Generated by Django 4.2.11 on 2026-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Default'), ('default', 'Violet Night'), ('midnight', 'Midnight'), ('emerald', 'Emerald'), ('sunset', 'Sunset')], default='light', max_length=20),
        ),
    ]
