# Generated by Django 4.2.11 on 2026-02-13 05:06

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/', validators=[courses.validators.validate_file_extension, courses.validators.validate_file_size]),
        ),
    ]
